config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'events/new'
  get 'events/create'
  devise_for :users
  resources :users, :only => [:show]
  
  resources :events do 
    post '/subscribe', to: 'events#subscribe'
    post '/unsubscribe', to: 'events#unsubscribe'
    get '/invite', to: 'events#invite' 
    post '/invite', to: 'events#invite'     
    post '/invite/:id', to: 'events#subscribe_friends', as: 'user_invited'
  end

  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User'
    has_and_belongs_to_many :attendees,class_name: 'User'
    
    monetize :price_cents, 
        numericality: {
            greater_than_or_equal_to: 0
        }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :created_events, class_name: 'Event', foreign_key: :creator_id
  has_and_belongs_to_many :attended_events, class_name: 'Event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new; end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur'
    )
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.creator_id = current_user.id
    if @event.save
      redirect_to event_path(@event)
      flash[:success] = 'Your event is created'
    else flash[:danger] = 'Your event is not create, please try again'
         render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
    else redirect_to event_path(@event)
         flash[:error] = 'YOUR EVENT IS NOT UPDATED. Please try again and make sure to update all the field.'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to user_path(current_user)
  end

  def subscribe
    @event = Event.find(params[:event_id])

    @amount = @event.price_cents
    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur'
    )

    @event.attendees << current_user
    redirect_to @event
    flash[:success] = 'You are now attending this event'
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to @event
  end

  def unsubscribe
    @event = Event.find(params[:event_id])
    @event.attendees.delete(current_user)
    redirect_to user_path(current_user)
    flash[:danger] = 'You are no longer attending this event'
  end

  private

  def event_params
    params.require(:event).permit(:description, :date, :place, :price)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    @events = Event.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return '' if resource.errors.empty?
  
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
      html = <<-HTML
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>
         #{pluralize(resource.errors.count, "error")} must be fixed
        </strong>
        #{messages}
      </div>
      HTML
  
      html.html_safe
    end
  end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: €5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="subscription"
          data-amount="500"
          data-currency="eur"
          data-locale="auto"></script>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<div class="jumbotron jumbotron-center shadow" style="background-color:#F8F9FA;">
  <center>
    <h1>EDITER</h1>
    <%= image_tag("https://www.indiaratings.co.in/Images/LandingPageImages/EventPage.jpg", class: "img-responsive" , :alt => "Homepage Events") %></center>

</div>

<div class="jumbotron jumbotron-center shadow" style="background-color:#F8F9FA;">
  <% if user_signed_in? %>

    <div class="col-sm-10 offset-sm-1 text-left">
      <%= form_for @event do |f| %>
      <%= f.label :DESCRIPTION %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :DATE %>
      <%= f.datetime_field :date, class: 'form-control' %>

      <%= f.label :LIEU %>
      <%= f.text_field :place, class: 'form-control' %>

      <%= f.label :PRIX %>
      <%= f.number_field :price, class: 'form-control', step: :any %></br>
    <div class="actions col-sm-10 offset-sm-1 text-center">
      <%= f.submit "METTRE A JOUR", class: "btn btn-orange btn-lg" %>
    </div>
  <% end %>
</div>
<%else%>
<%flash[:error] = "VOUS N'ETES PAS CONNECTÉ"%><%end%>
</div>

app/views/events/index.html.erb
<div class="jumbotron jumbotron-center" style="background-color:#F8F9FA;">
  <center>
    <h1>TOUS LES ÉVÉNEMENTS</h1>
    <%= image_tag("https://www.newstatesman.com/sites/all/themes/creative-responsive-theme/images/new_statesman_events.jpg", class: "img-fluid" , :alt => "Homepage Events") %></center>

</div>

<div class="jumbotron jumbotron-center" style="background-color:#F8F9FA;">

  <% if user_signed_in? %>
    <div class="container-fluid">
      <table class="table">
        <tr>

          <th>NOM</th>
          <th>DATE</th>
          <th>LIEUX</th>
          <th>PARTICIPANTS</th>
          <th>TARIFS</th>
          <th>STATUS</th>
          <th>PLUS</th>

        </tr>

        <% @events.each do |event| %>
          <tr>
            <td><%= event.description %></td>
            <td><%= event.date.to_date.strftime("%v")%></td>
            <td><%= event.place%></td>
            <td><%= event.attendees.count %></td>
            <td><%= humanized_money_with_symbol(event.price) %></td>

            <%if event.date.today?%>
              <td>
                <span class="badge badge-success">EN COURS</span>
                <%elsif event.date.past?%>
                  <td>
                    <span class="badge badge-danger">TERMINE</span></td>
                  <%elsif event.date.future?%>
                    <td>
                      <span class="badge badge-info">A VENIR</span></td>

                  <% end %>
                  <td><%= link_to "EN SAVOIR PLUS", event_path(event.id) %></td>
                </tr>
              <% end %>
            </table>
          </div>
        <%else%>
          <%flash[:error] = "VOUS N'ETES PAS CONNECTÉ"%><%end%>

        </div>

app/views/events/new.html.erb
<div class="jumbotron jumbotron-center shadow" style="background-color:#F8F9FA;">
  <% if user_signed_in? %>
    <% provide(:title, 'New event') %>
      <h1 style="text-align:center; padding-top:50px; color:#007f8c;">CRÉER UN NOUVEL ÉVÉNEMENT</h1>

      <div class="col-sm-10 offset-sm-1 ">
        <%= form_for(@event) do |f| %>
        <%= f.label :DESCRIPTION %>
        <%= f.text_field :description, class: 'form-control' %>

        <%= f.label :DATE %>
        <%= f.datetime_field :date, class: 'form-control' %>

        <%= f.label :LIEU %>
        <%= f.text_field :place, class: 'form-control' %>

        <%= f.label :PRIX %>
        <%= f.number_field :price, class: 'form-control', step: :any %></br>
      <div class="actions col-sm-10 offset-sm-1 text-center">
        <%= f.submit "VALIDER", class: "btn btn-orange btn-lg" %>
      </div>
    <% end %>
  </div>
<%else%>
  <%flash[:error] = "Vous devez d'abord être connecté"%><%end%>
</div>

app/views/events/old-invite.html.erb
<div class="jumbotron jumbotron-center shadow" style="background-color:#F8F9FA;">
  <% if user_signed_in? %>
    <div class="container">
      <table class="table">
        <tr>
          <h1>LISTE DES PARTICIPANTS<h1>

              <th>NOM</th>
              <th>INVITE</th>
            </tr>

            <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <%if @event.attendees.include?(user)%>
                  <td>
                    <span class="badge-danger">
                      <%=user.name%>
                      participe</span></td>
                <%else%>
                  <td><%= button_to "INVITER", event_user_invited_path(@event.id, user.id), :class => 'btn btn-success' %></td>
                <%end%>
              </tr>
            <% end %>
          </table>
        </div>
      <%else%>
        <%flash[:error] = "Vous devez d'abord être connecté"%><%end%>

      </div>

app/views/events/show.html.erb
<div class="container-fluid" style="padding: 50px;">

  <% if user_signed_in? %>

    <div class="jumbotron jumbotron-center shadow" style="background-color:#F8F9FA;">
      <center>
        <h1>Nom de l'événement :
          <%= @event.description %></h1>
        <%= image_tag("https://www.indiaratings.co.in/Images/LandingPageImages/EventPage.jpg", class: "img-responsive" , :alt => "Homepage Events") %></center>

    </div>

    <div class="jumbotron jumbotron-center shadow" style="background-color:#F8F9FA;">
      <center>
        <p>
          LIEU :
          <%= @event.place %><br/>
          DATE :
          <%= @event.date.strftime("%v") %>
          <br>
            ORGANISATEUR:
            <%= link_to @event.creator.name, user_path(@event.creator.id) %></br>
          TARIF :
          <%= humanized_money_with_symbol(@event.price) %></br>
        MISE A JOUR :
        <%= @event.updated_at.to_date.strftime("%v") %></br>
      <%if @event.date.future?%>
        <%if @event.attendees.include?(current_user)%>
          <%= button_to "Ne plus participer à cet event", event_unsubscribe_path(@event), :class => 'btn btn-danger' %>
          <%elsif @event.creator == current_user%>
            <span class="badge badge-info">
              Vous êtes l'organisateur</span></td>
        <%else%>
          <%= form_tag event_subscribe_path(@event) do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
          </article>
          <script
            src="https://checkout.stripe.com/checkout.js"
            class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="<%= @event.place %> le <%= @event.date.to_date.strftime("
            %a,="%a,"
            %d="%d"
            %b="%b"
            %y") %>"="%Y") %>""
            data-amount="<% @event.price_cents %>"
            data-currency="EUR"
            data-locale="auto"></script>
        <% end %>
      <%end%>
      <%elsif @event.date.past?%>
        <span class="badge badge-danger">Vous ne pouvez pas participer à un event déjà passé</span></td>
    <%end%>
  </p>
</center>
</div>

<div class="jumbotron jumbotron-center shadow" style="background-color:#F8F9FA;">
<center>
  <h2>Liste des Participants</h2>
</center>

<table class="table">
  <tr>
    <th>NOM</th>
    <th>PROFIL</th>
  </tr>
  <% @event.attendees.each do |attendee| %>
    <tr>
      <td><%= attendee.name%></td>
      <td><%= link_to 'profil', user_path(attendee.id)%></td>
    </tr>
  <%end%>
</table>

</div>

<%else%>
<%flash[:error] = "VOUS N'ETES PAS CONNECTÉ"%><%end%>

</div>

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer class="page-footer font-small stylish-color-dark pt-4 mt-4">

  <!--Footer Links-->
  <div class="container text-center text-md-left">

    <!-- Footer links -->
    <div class="row text-center text-md-left mt-3 pb-3">

      <!--First column-->
      <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Eventbrite</h6>
        <p>Eventbrite est la plus grande plateforme technologique de billetterie en libre-service au monde.</p>
      </div>
      <!--/.First column-->

      <hr class="w-100 clearfix d-md-none">

      <!--Second column-->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
        <p>
          <a href="https://www.eventbrite.com/d/ma--boston/events/">Boston Events</a>
        </p>
        <p>
          <a href="https://www.eventbrite.com/d/il--chicago/events/">Chicago Events</a>
        </p>
        <p>
          <a href="https://www.eventbrite.com/d/co--denver/events/">Denver Events</a>
        </p>
        <p>
          <a href="https://www.eventbrite.com/d/tx--houston/events/">Houston Events</a>
        </p>
      </div>
      <!--/.Second column-->

      <hr class="w-100 clearfix d-md-none">

      <!--Third column-->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Connect With Us</h6>
        <p>
          <a href="https://www.eventbrite.com/support/contact-us">Contact Support</a>
        </p>
        <p>
          <a href="https://www.eventbrite.com/l/contact-sales/">Contact Sales</a>
        </p>
        <p>
          <a href="https://www.twitter.com/Eventbrite">Twitter</a>
        </p>
        <p>
          <a href="https://www.facebook.com/Eventbrite">Facebook</a>
        </p>
      </div>
      <!--/.Third column-->

      <hr class="w-100 clearfix d-md-none">

      <!--Fourth column-->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
        <p>
          <i class="fa fa-home mr-3"></i>Rachid B. racö</p>
        <p>
          <i class="fa fa-envelope mr-3"></i>
          <a href="https://github.com/raco82">Github</a>
          <p>
            <i class="fa fa-phone mr-3"></i>
            <a href="https://www.instagram.com/agenceaixit/">Aixit</a>
            <p>
              <i class="fa fa-print mr-3"></i>
              <a href="https://www.instagram.com/l.humeur.du.jour/">HDJ</a>
            </div>
            <!--/.Fourth column-->

          </div>
          <!-- Footer links -->

          <hr>

          <div class="row py-3 d-flex align-items-center">

            <!--Grid column-->
            <div class="col-md-8 col-lg-8">

              <!--Copyright-->
              <p class="text-center text-md-left grey-text">Site réalisé avec ❤️ sous
                <a href="http://rubyonrails.org/">Ruby on Rails</a>
                par
                <a href="https://www.instagram.com/l.humeur.du.jour/">
                  <strong>Racö</strong>
                </a>
              </p>
              <!--/.Copyright-->

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-4 col-lg-4 ml-lg-0">

              <!--Social buttons-->
              <div class="text-center text-md-right">
                <ul class="list-unstyled list-inline">
                  <li><%= link_to "Aixit", "http://aixit.fr" %></li>
                </ul>
              </div>
              <!--/.Social buttons-->

            </div>
            <!--Grid column-->

          </div>

        </div>

      </footer>
      <!--/.Footer-->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">

    <a class="navbar-brand" href="/">
      <img src="https://www.freshbooks.com/_themes/freshbooks/smux-assets/img/content/addons/Eventbrite_wordmark_orange.png" width="120" height="30" alt="Logo Eventbrite">
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarToggler">

      <ul class="navbar-nav ml-auto">

        <%if user_signed_in?%>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">PROFIL</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown"><a class="dropdown-item" <%= link_to 'MON PROFIL', current_user %></a>
          <a class="dropdown-item" <%= link_to 'EDITER PROFILE', edit_user_registration_path %></a>
          <div class="dropdown-divider"></div>
        <a class="dropdown-item" <%= link_to 'SE DECONNECTER', destroy_user_session_path, method: :delete %></a>
      </div>
    </li>
  <a class="nav-item nav-link" <%= link_to 'CRÉER UN ÉVÉNEMENT', new_event_path %></a>
<a class="nav-item nav-link" <%= link_to 'LES ÉVÉNEMENTS', events_path %></a>

<%else%>
<a class="nav-item nav-link" <%= link_to 'CRÉER UN COMPTE', new_user_registration_path %></a>
<a class="nav-item nav-link" <%= link_to 'SE CONNECTER', new_user_session_path %></a>
<%end%>

</ul>

</div>

</div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RAILS EVENTBRITE DEVISE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>
  </head>

  <body class="showcase">
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/messages' %>

    </div>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/show.html.erb
<div class="container-fluid" style="padding: 50px;">

  <% if user_signed_in? %>

    <div class="jumbotron jumbotron-center shadow" style="background-color:#F8F9FA;">
      <center>
        <h1>PROFIL DE :
          <%=@user.name%></h1>
        <%= image_tag("https://www.indiaratings.co.in/Images/LandingPageImages/EventPage.jpg", class: "img-responsive" , :alt => "Homepage Events") %></center>

    </div>

    <div class="jumbotron jumbotron-center shadow" style="background-color:#F8F9FA;">
      <center>
        <p>
          MEMBRE EVENTBRITE DEPUIS :
          <%= @user.created_at.to_date.strftime("%v")%></br>
        NOMBRE D'ÉVÉNEMENTS ORGANISÉS :
        <%=@user.created_events.count%></br>
      NOMBRE D'ÉVÉNEMENTS SUIVIS :
      <%=@user.attended_events.count%></br>
  </p>
</center>
</div>

<div class="jumbotron jumbotron-center shadow" style="background-color:#F8F9FA;">
<center>

  <h2>MES ÉVÉNEMENTS</h2>

  <table class="table">
    <tr>
      <th>NOM</th>
      <th>DATE</th>
      <th>LIEUX</th>
      <th>PARTICIPANTS</th>
      <th>STATUS</th>
      <th>MODIFIER</th>
      <th>SUPPRIMER</th>
    </tr>

    <% @user.created_events.each do |event| %>
      <tr>
        <td><%= event.description %></td>
        <td><%= event.date.to_date.strftime("%v")%>
          <td><%= event.place%></td>
          <td><%= event.attendees.count %></td>
          <%if event.date.today?%>
            <td>
              <span class="badge badge-success">EN COURS</span>
              <%elsif event.date.past?%>
                <td>
                  <span class="badge badge-danger">TERMINE</span></td>
                <%elsif event.date.future?%>
                  <td>
                    <span class="badge badge-info">A VENIR</span></td>
                <% end %>

                <% if current_user.id == event.creator.id %>
                  <td><%=link_to 'MODIFIER', edit_event_path(event)%></td>
                  <td><%= link_to 'SUPPRIMER', event, method: :delete %></td>
                </br>
              </br>
            <%else%>
              <td>No access</td>
              <td>No access</td>
            <%end%>
          </tr>
        <%end%>
      </table>
    </br>
  </br>
  <h2>ÉVÉNEMENTS SUIVIS</h2>
  <table class="table">
    <tr>
      <th>NOM</th>
      <th>DATE</th>
      <th>LIEUX</th>
      <th>PARTICIPANTS</th>
      <th>STATUS</th>
    </tr>
    <% @user.attended_events.each do |event| %>
      <tr>
        <td><%= event.description %></td>
        <td><%= event.date.to_date.strftime("%v")%></td>
        <td><%= event.place%></td>
        <td><%= event.attendees.count %></td>
        <%if event.date.today?%>
          <td>
            <span class="badge badge-success">EN COURS</span>
            <%elsif event.date.past?%>
              <td>
                <span class="badge badge-danger">TERMINE</span></td>
              <%elsif event.date.future?%>
                <td>
                  <span class="badge badge-info">A VENIR</span></td>
              <% end %>
            </tr>
          <%end%>
        </table>

      <%else%>
        <%flash[:error] = "Your must sign in or sign up first"%><%end%>
      </div>

    </center>
  </div>

</div>